language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - LIBSTDC_VERSION=5
    - CLANG_VERSION=3.6
  allow_failures:
  - compiler: clang

matrix:
  allow_failures:
    - compiler: clang

before_install:
  - if [[ "$CXX" == "g++" || "$CC" == "gcc" ]]; then ./scripts/gcc.sh; fi
  - if [[ "$CXX" == "clang++" || "$CC" == "clang" ]]; then ./scripts/clang.sh; fi

script:
  - make clean && make

notifications:
  email: false

sudo: required

cache:
  - apt
