language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - LIBSTDC_VERSION=5
    - CLANG_VERSION=3.6
  allow_failures:
  - compiler: clang

matrix:
  allow_failures:
    - compiler: clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - h-rayflood/llvm
    - h-rayflood/llvm-upper
    - h-rayflood/gcc-upper

    packages:
    - cmake
    - gcc-5.0
    - g++-5.0
    - clang

before_install:
  - if [[ "$CXX" == "g++" || "$CC" == "gcc" ]]; then ./scripts/gcc.sh; fi
  - if [[ "$CXX" == "clang++" || "$CC" == "clang" ]]; then ./scripts/clang.sh; fi

script:
  - make clean && make

notifications:
  email: false

sudo: required

cache:
  - apt
